application: mythic-fire-634
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /rootcert
  static_files: MediaServer_CA.crt
  upload: MediaServer_CA\.crt
  
- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
